repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    - id: mypy
      files: sphinx_needs/.*
      args: []
      additional_dependencies:
      - sphinx==6
      - types-docutils
      - types-jsonschema
      - types-requests

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check

  - repo: local
    hooks:
      - id: check-readme
        name: check-readme
        files: README.rst
        language: python
        entry: rst2html.py README.rst --halt=warning
        pass_filenames: false
        additional_dependencies:
        - docutils==0.20.1
        - pygments
